// Mock listings used as fallback when the Worker API is unavailable.
// Neighborhoods match the cdmx-neighborhoods.geojson colonia names.
export const MOCK_LISTINGS = [
  { id: 'm1', title: 'Departamento moderno en Condesa con balcón', price: 22000, neighborhood: 'Condesa', size: 75, bedrooms: 2, image: null, url: 'https://www.inmuebles24.com', source: 'inmuebles24' },
  { id: 'm2', title: 'Estudio amueblado Roma Norte, piso 8', price: 15500, neighborhood: 'Roma Norte', size: 42, bedrooms: 1, image: null, url: 'https://www.vivanuncios.com.mx', source: 'vivanuncios' },
  { id: 'm3', title: 'Casa en Coyoacán 3 recámaras jardín privado', price: 28000, neighborhood: 'Coyoacán', size: 160, bedrooms: 3, image: null, url: 'https://www.lamudi.com.mx', source: 'lamudi' },
  { id: 'm4', title: 'Departamento Narvarte amplio, muy iluminado', price: 14000, neighborhood: 'Narvarte Poniente', size: 80, bedrooms: 2, image: null, url: 'https://www.inmuebles24.com', source: 'inmuebles24' },
  { id: 'm5', title: 'Loft ejecutivo en Polanco amueblado', price: 35000, neighborhood: 'Polanco', size: 65, bedrooms: 1, image: null, url: 'https://www.lamudi.com.mx', source: 'lamudi' },
  { id: 'm6', title: 'Depto. Del Valle 2 recámaras céntrico', price: 16500, neighborhood: 'Del Valle', size: 90, bedrooms: 2, image: null, url: 'https://www.vivanuncios.com.mx', source: 'vivanuncios' },
  { id: 'm7', title: 'Penthouse Santa Fe vista panorámica', price: 48000, neighborhood: 'Santa Fe', size: 180, bedrooms: 3, image: null, url: 'https://www.lamudi.com.mx', source: 'lamudi' },
  { id: 'm8', title: 'Departamento económico Doctores planta baja', price: 9000, neighborhood: 'Doctores', size: 55, bedrooms: 1, image: null, url: 'https://www.inmuebles24.com', source: 'inmuebles24' },
  { id: 'm9', title: 'Casa Tlalpan 4 recámaras con estacionamiento', price: 18000, neighborhood: 'Tlalpan', size: 200, bedrooms: 4, image: null, url: 'https://www.vivanuncios.com.mx', source: 'vivanuncios' },
  { id: 'm10', title: 'Estudio amueblado Benito Juárez con terraza', price: 13000, neighborhood: 'Benito Juárez', size: 38, bedrooms: 1, image: null, url: 'https://www.inmuebles24.com', source: 'inmuebles24' },
  { id: 'm11', title: 'Depto. Roma Sur 2 recámaras edificio nuevo', price: 19500, neighborhood: 'Roma Sur', size: 85, bedrooms: 2, image: null, url: 'https://www.vivanuncios.com.mx', source: 'vivanuncios' },
  { id: 'm12', title: 'Casa Coyoacán cerca de Viveros 3 recámaras', price: 25000, neighborhood: 'Villa Coyoacán', size: 140, bedrooms: 3, image: null, url: 'https://www.lamudi.com.mx', source: 'lamudi' },
  { id: 'm13', title: 'Departamento Condesa planta alta balcón', price: 20000, neighborhood: 'Hipódromo Condesa', size: 70, bedrooms: 2, image: null, url: 'https://www.lamudi.com.mx', source: 'lamudi' },
  { id: 'm14', title: 'Estudio moderno Centro Histórico zona Rosa', price: 11500, neighborhood: 'Centro Histórico', size: 40, bedrooms: 1, image: null, url: 'https://www.inmuebles24.com', source: 'inmuebles24' },
  { id: 'm15', title: 'Casa Azcapotzalco 3 recámaras con patio', price: 12000, neighborhood: 'Azcapotzalco', size: 120, bedrooms: 3, image: null, url: 'https://www.vivanuncios.com.mx', source: 'vivanuncios' },
  { id: 'm16', title: 'Departamento Polanco lujo 2 recámaras', price: 42000, neighborhood: 'Polanco', size: 110, bedrooms: 2, image: null, url: 'https://www.lamudi.com.mx', source: 'lamudi' },
  { id: 'm17', title: 'Lomas de Chapultepec casa con jardín', price: 55000, neighborhood: 'Lomas de Chapultepec', size: 300, bedrooms: 4, image: null, url: 'https://www.lamudi.com.mx', source: 'lamudi' },
  { id: 'm18', title: 'Guerrero studio accesible 1 rec.', price: 7500, neighborhood: 'Guerrero', size: 35, bedrooms: 1, image: null, url: 'https://www.vivanuncios.com.mx', source: 'vivanuncios' },
  { id: 'm19', title: 'Tlatelolco depto amplio con amenidades', price: 14000, neighborhood: 'Tlatelolco', size: 95, bedrooms: 2, image: null, url: 'https://www.inmuebles24.com', source: 'inmuebles24' },
  { id: 'm20', title: 'Santa Fe corporativo amueblado 1 rec.', price: 30000, neighborhood: 'Santa Fe Norte', size: 55, bedrooms: 1, image: null, url: 'https://www.lamudi.com.mx', source: 'lamudi' },
  { id: 'm21', title: 'Mixcoac 2 recámaras acceso a Periferico', price: 15000, neighborhood: 'Mixcoac', size: 80, bedrooms: 2, image: null, url: 'https://www.vivanuncios.com.mx', source: 'vivanuncios' },
  { id: 'm22', title: 'Iztapalapa casa 4 rec. muy buena ubicación', price: 8000, neighborhood: 'Iztapalapa', size: 130, bedrooms: 4, image: null, url: 'https://www.inmuebles24.com', source: 'inmuebles24' },
  { id: 'm23', title: 'Portales Norte depto 2 rec. transporte inmediato', price: 13500, neighborhood: 'Portales Norte', size: 70, bedrooms: 2, image: null, url: 'https://www.vivanuncios.com.mx', source: 'vivanuncios' },
  { id: 'm24', title: 'Lindavista depto luminoso 2 rec. balcón', price: 14500, neighborhood: 'Lindavista', size: 75, bedrooms: 2, image: null, url: 'https://www.inmuebles24.com', source: 'inmuebles24' },
  { id: 'm25', title: 'Vallejo studio moderno recién remodelado', price: 9500, neighborhood: 'Vallejo', size: 40, bedrooms: 1, image: null, url: 'https://www.lamudi.com.mx', source: 'lamudi' },
  { id: 'm26', title: 'Escandón 2 rec. cerca de parque', price: 18000, neighborhood: 'Escandón', size: 85, bedrooms: 2, image: null, url: 'https://www.vivanuncios.com.mx', source: 'vivanuncios' },
  { id: 'm27', title: 'Del Valle Norte piso 3 con elevador', price: 17000, neighborhood: 'Del Valle Norte', size: 90, bedrooms: 2, image: null, url: 'https://www.inmuebles24.com', source: 'inmuebles24' },
  { id: 'm28', title: 'San Ángel casa con estudio 3 rec.', price: 32000, neighborhood: 'San Ángel', size: 180, bedrooms: 3, image: null, url: 'https://www.lamudi.com.mx', source: 'lamudi' },
  { id: 'm29', title: 'Iztacalco depto 2 rec. cerca del Metro', price: 10000, neighborhood: 'Iztacalco', size: 60, bedrooms: 2, image: null, url: 'https://www.vivanuncios.com.mx', source: 'vivanuncios' },
  { id: 'm30', title: 'Obrera studio 1 rec. bien comunicado', price: 8500, neighborhood: 'Obrera', size: 38, bedrooms: 1, image: null, url: 'https://www.inmuebles24.com', source: 'inmuebles24' },
]
